/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weatherapp;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
/**
 *
 * @author tylerreardon
 */
public class Preferences extends javax.swing.JFrame {
    List<City> cities = new ArrayList();
    /**
     * Creates new form Preferences
     */
    public Preferences() {
        initComponents();
        ReadFromFile file = new ReadFromFile();
        cities = file.makeCities();
        
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i<cities.size(); i++)
        {
            listModel.addElement(cities.get(i).getCityName());
        }

        CitiesList.setModel(listModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enter = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        PreferencesLabel = new javax.swing.JLabel();
        CityListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CitiesList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Enter.setBackground(new java.awt.Color(0, 167, 255));
        Enter.setText("Enter");
        getContentPane().add(Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 251, -1, -1));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 251, -1, -1));

        PreferencesLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        PreferencesLabel.setText("Preferences");
        getContentPane().add(PreferencesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        CityListLabel.setText("Choose City:");
        getContentPane().add(CityListLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, -1, -1));

        CitiesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(CitiesList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, 199, 174));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed
                             

    /**
     */
    public static void runPreferences() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preferences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JList CitiesList;
    private javax.swing.JLabel CityListLabel;
    private javax.swing.JButton Enter;
    private javax.swing.JLabel PreferencesLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
