/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam1;

import java.io.FileNotFoundException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Represents the Under Over game
 * @author tylerreardon
 */
public class UnderOverUI extends javax.swing.JFrame {

    FileIO file = new FileIO();
    ArrayList<Player> players = new ArrayList<>();
    private static Player _player;

    /**
     * Creates new form UnderOverUI
     */
    public UnderOverUI() throws FileNotFoundException {
        initComponents();
        players = file.readPlayers(); //makes an ArrayList of players
        userName.setText("UserName: " + _player.getUserName()); //sets the username label
        money.setText("Money: $" + _player.getMoney()); //sets the money label
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        underOverDescr = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        bet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        messageCenter = new javax.swing.JLabel();
        betMessage = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        underOverDescr.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        underOverDescr.setText("Under Over Game");

        userName.setText("Name:");

        money.setText("Money Available:");

        jLabel1.setText("Bet:");

        play.setText("Play!");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        betMessage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Under 7", "Over 7", "Exactly 7" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(underOverDescr)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(play)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(bet, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(money)
                                .addComponent(userName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(underOverDescr)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(betMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(money)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(play)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * When the user presses the play button
     * @param evt 
     */
    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        double betAmount = 0;
        double playerMoney = 0;
        boolean won;
        String betMessageString;
        int diceSum;
        
        //check to see if the user inputted a valid number
        try {
            betAmount = Double.parseDouble(bet.getText());
            if (betAmount<0){ //check if the number is not negative
                messageCenter.setText("Cannot have a negative number!");
                return;
            }
            playerMoney = Double.parseDouble(_player.getMoney());
            betMessageString = (String) betMessage.getSelectedItem();

        } catch (Exception e) {
            //notify users what they did wrong
            messageCenter.setText("Invalid input! Must be a number.");
            return;
        }

        //begin the round
        try {
            Round round = new Round(betAmount, _player, betMessageString);
            won = round.runRound();
            
            players = file.readPlayers(); //update the players array
            
            //update the money label
            for (int i = 0; i<players.size(); i++){
                if (_player.getUserName().equals(players.get(i).getUserName())){
                    money.setText("Money: $" + players.get(i).getMoney());
                }
            }
            
            //notify the user if they won or lost
            diceSum = round.getDiceSum();
            if (won){
                messageCenter.setText("Dice Roll: "+ diceSum + " ---> You won!");
            }else{
                messageCenter.setText("Dice Roll: " + diceSum + " ---> You lost...");
            }
 
        } catch (Exception e) {
            System.out.printf("%s", e.getMessage());
        }
    }//GEN-LAST:event_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void runUnderOverUI(Player player) {
        _player = player;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UnderOverUI().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(UnderOverUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bet;
    private javax.swing.JComboBox betMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel messageCenter;
    private javax.swing.JLabel money;
    private javax.swing.JButton play;
    private javax.swing.JLabel underOverDescr;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
